apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: demo-deployment 
=======
  name: deployment
>>>>>>> afae42cf966804b3cba7cddbe931d730799c00ce
spec:
  replicas: 1
  selector:
    matchLabels:
<<<<<<< HEAD
      app : demo-deployment
  template:
    metadata:
      labels:
        app : demo-deployment
    spec:
      serviceAccountName: dm-incluster
      containers:
        - name: demo-deployment
=======
      app : deployment
  template:
    metadata:
      labels:
        app : deployment
    spec:
      serviceAccountName: dm-incluster
      containers:
        - name: deployment
>>>>>>> afae42cf966804b3cba7cddbe931d730799c00ce
          image: acs108118/incluster:latest
          imagePullPolicy: IfNotPresent
